# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d522e62018cfc26f5d36bfeddc728b86a80c50a0b03bd3e2a383086976cf77f78e1cceeccdbe49a4974a2f6f8d0b85aea8e98722e060623c76e3fcbbdd0671b0
  stripe_secret: <%= ENV.fetch( "STRIPE_SECRET_KEY" ,"sk_test_jEqqFTaEIr5d2rGn5di9ghcT") %>
  stripe_public: <%= ENV.fetch( "STRIPE_PUBLIC_KEY" ,"pk_test_6YjbSqtBimrVOeRNngdNy3Gu") %>

test:
  secret_key_base: ab6b4ba9ea75c1a0a91c1bdcd75d51be3fb0e9543a179af19b5262c90efc92c7dff28c317d7e0503212eb0c437ecc28b5b06ab7cafddf407cf99b036f44ee10b

# Do not keep production secrets in the repository,
# instead read values from the environment.
# TODO: WHEN LAUNCHED, REMOVE THE FALLBACK TEST ENV KEYS
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret: <%= ENV.fetch( "STRIPE_SECRET_KEY" ,"sk_test_jEqqFTaEIr5d2rGn5di9ghcT") %>
  stripe_public: <%= ENV.fetch( "STRIPE_PUBLIC_KEY" ,"pk_test_6YjbSqtBimrVOeRNngdNy3Gu") %>
