class CountiesProvinces
  def self.state_options
    [
      ["Alabama", :AL, { class: "US" }],
      ["Alaska", :AK, { class: "US" }],
      ["Arizona", :AZ, { class: "US" }],
      ["Arkansas", :AR, { class: "US" }],
      ["California", :CA, { class: "US" }],
      ["Colorado", :CO, { class: "US" }],
      ["Connecticut", :CT, { class: "US" }],
      ["Delaware", :DE, { class: "US" }],
      ["District of Columbia", :DC, { class: "US" }],
      ["Florida", :FL, { class: "US" }],
      ["Georgia", :GA, { class: "US" }],
      ["Hawaii", :HI, { class: "US" }],
      ["Idaho", :ID, { class: "US" }],
      ["Illinois", :IL, { class: "US" }],
      ["Indiana", :IN, { class: "US" }],
      ["Iowa", :IA, { class: "US" }],
      ["Kansas", :KS, { class: "US" }],
      ["Kentucky", :KY, { class: "US" }],
      ["Louisiana", :LA, { class: "US" }],
      ["Maine", :ME, { class: "US" }],
      ["Maryland", :MD, { class: "US" }],
      ["Massachusetts", :MA, { class: "US" }],
      ["Michigan", :MI, { class: "US" }],
      ["Minnesota", :MN, { class: "US" }],
      ["Mississippi", :MS, { class: "US" }],
      ["Missouri", :MO, { class: "US" }],
      ["Montana", :MT, { class: "US" }],
      ["Nebraska", :NE, { class: "US" }],
      ["Nevada", :NV, { class: "US" }],
      ["New Hampshire", :NH, { class: "US" }],
      ["New Jersey", :NJ, { class: "US" }],
      ["New Mexico", :NM, { class: "US" }],
      ["New York", :NY, { class: "US" }],
      ["North Carolina", :NC, { class: "US" }],
      ["North Dakota", :ND, { class: "US" }],
      ["Ohio", :OH, { class: "US" }],
      ["Oklahoma", :OK, { class: "US" }],
      ["Oregon", :OR, { class: "US" }],
      ["Pennsylvania", :PA, { class: "US" }],
      ["Puerto Rico", :PR, { class: "US" }],
      ["Rhode Island", :RI, { class: "US" }],
      ["South Carolina", :SC, { class: "US" }],
      ["South Dakota", :SD, { class: "US" }],
      ["Tennessee", :TN, { class: "US" }],
      ["Texas", :TX, { class: "US" }],
      ["Utah", :UT, { class: "US" }],
      ["Vermont", :VT, { class: "US" }],
      ["Virginia", :VA, { class: "US" }],
      ["Washington", :WA, { class: "US" }],
      ["West Virginia", :WV, { class: "US" }],
      ["Wisconsin", :WI, { class: "US" }],
      ["Wyoming", :WY, { class: "US" }],


      ["Alberta", :AB, { class: "CA" }],
      ["British Columbia", :BC, { class: "CA" }],
      ["Manitoba", :MB, { class: "CA" }],
      ["New Brunswick", :NB, { class: "CA" }],
      ["Newfoundland and Labrador", :NL, { class: "CA" }],
      ["Northwest Territories", :NT, { class: "CA" }],
      ["Nova Scotia", :NS, { class: "CA" }],
      ["Nunavut", :NU, { class: "CA" }],
      ["Ontario", :ON, { class: "CA" }],
      ["Prince Edward Island", :PE, { class: "CA" }],
      ["Quebec", :QC, { class: "CA" }],
      ["Saskatchewan", :SK, { class: "CA" }],
      ["Yukon", :YT, { class: "CA" }],


      ["New South Wales", :NSW, { class: "AU" }],
      ["Queensland", :QLD, { class: "AU" }],
      ["South Australia", :SA, { class: "AU" }],
      ["Tasmania", :TAS, { class: "AU" }],
      ["Victoria", :VIC, { class: "AU" }],
      ["Western Australia", :WA, { class: "AU" }],
      ["Australian Capital Territory", :ACT, { class: "AU" }],
      ["Jervis Bay Territory", :JBT, { class: "AU" }],
      ["Northern Territory", :NT, { class: "AU" }]
    ]
  end

end